package com.moting.spring.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table menu
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_identify
     *
     * @mbggenerated
     */
    private String menuIdentify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.nenu_name
     *
     * @mbggenerated
     */
    private String nenuName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_id
     *
     * @return the value of menu.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_id
     *
     * @param menuId the value for menu.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_identify
     *
     * @return the value of menu.menu_identify
     *
     * @mbggenerated
     */
    public String getMenuIdentify() {
        return menuIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_identify
     *
     * @param menuIdentify the value for menu.menu_identify
     *
     * @mbggenerated
     */
    public void setMenuIdentify(String menuIdentify) {
        this.menuIdentify = menuIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.nenu_name
     *
     * @return the value of menu.nenu_name
     *
     * @mbggenerated
     */
    public String getNenuName() {
        return nenuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.nenu_name
     *
     * @param nenuName the value for menu.nenu_name
     *
     * @mbggenerated
     */
    public void setNenuName(String nenuName) {
        this.nenuName = nenuName;
    }
}